name:                lucid-from-html-app
version:             0.1.0.0
github:              "githubuser/lucid-from-html-app"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/lucid-from-html-app#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant
- lucid
- lucid-htmx
- lucid-alpine
- servant-server
- lucid-from-html
- text
- servant-lucid
- warp
- warp-tls

library:
  source-dirs: src

executables:
  lucid-from-html-app-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lucid-from-html-app

tests:
  lucid-from-html-app-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lucid-from-html-app
